-- Phase 5-6: campaigns, dynamic banners and growth analytics.
create table if not exists public.growth_campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  status text not null default 'draft' check (status in ('draft','scheduled','active','paused','completed')),
  starts_at timestamptz,
  ends_at timestamptz,
  offer_ids uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.growth_banners (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  message text,
  badge_text text,
  cta_text text,
  cta_url text,
  placement text not null default 'landing' check (placement in ('landing','pricing','billing','dashboard')),
  style text not null default 'premium' check (style in ('info','success','warning','premium')),
  active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  priority integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.growth_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  offer_id uuid references public.admin_promo_codes(id) on delete set null,
  banner_id uuid references public.growth_banners(id) on delete set null,
  plan text,
  billing_cycle text,
  amount numeric,
  page_path text,
  referrer text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists growth_campaigns_status_idx on public.growth_campaigns(status, starts_at, ends_at);
create index if not exists growth_banners_active_idx on public.growth_banners(active, placement, priority, starts_at, ends_at);
create index if not exists growth_events_name_created_idx on public.growth_events(event_name, created_at desc);

alter table public.growth_campaigns enable row level security;
alter table public.growth_banners enable row level security;
alter table public.growth_events enable row level security;

drop policy if exists public_read_active_growth_banners on public.growth_banners;
create policy public_read_active_growth_banners on public.growth_banners for select to anon, authenticated using (
  active = true and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at >= now())
);

drop policy if exists public_insert_growth_events on public.growth_events;
create policy public_insert_growth_events on public.growth_events for insert to anon, authenticated with check (true);

-- Admin policies use the same owner email convention as the existing Rivox admin panel.
drop policy if exists admin_manage_growth_campaigns on public.growth_campaigns;
create policy admin_manage_growth_campaigns on public.growth_campaigns for all to authenticated
using ((auth.jwt() ->> 'email') = 'mz7123272@gmail.com')
with check ((auth.jwt() ->> 'email') = 'mz7123272@gmail.com');

drop policy if exists admin_manage_growth_banners on public.growth_banners;
create policy admin_manage_growth_banners on public.growth_banners for all to authenticated
using ((auth.jwt() ->> 'email') = 'mz7123272@gmail.com')
with check ((auth.jwt() ->> 'email') = 'mz7123272@gmail.com');

drop policy if exists admin_read_growth_events on public.growth_events;
create policy admin_read_growth_events on public.growth_events for select to authenticated
using ((auth.jwt() ->> 'email') = 'mz7123272@gmail.com');
