import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { useAuth } from "../context/AuthContext";
import BrandStudio from "../components/BrandStudio";
import { DEFAULT_BRANDING, type WorkspaceBranding } from "../lib/branding";

type Tab="analytics"|"branding"|"api"|"webhooks"|"audit";
const events=["invoice.created","invoice.paid","invoice.overdue","customer.created","customer.updated","subscription.updated"];

export default function Business(){
 const {profile}=useAuth(); const [tab,setTab]=useState<Tab>("analytics"); const [workspaceId,setWorkspaceId]=useState(""); const [message,setMessage]=useState("");
 const [branding,setBranding]=useState<WorkspaceBranding>(DEFAULT_BRANDING); const [apiKeys,setApiKeys]=useState<any[]>([]); const [newKey,setNewKey]=useState("");
 const [hooks,setHooks]=useState<any[]>([]); const [deliveries,setDeliveries]=useState<any[]>([]); const [hookUrl,setHookUrl]=useState(""); const [hookEvents,setHookEvents]=useState<string[]>(["invoice.paid"]); const [logs,setLogs]=useState<any[]>([]); const [filter,setFilter]=useState("");
 const [invoices,setInvoices]=useState<any[]>([]); const [clients,setClients]=useState<any[]>([]); const isBusiness=profile?.plan==="business";
 const load=useCallback(async()=>{if(!isBusiness)return; const {data:wid}=await supabase.rpc("ensure_workspace_for_owner",{p_owner:profile?.user_id}); if(!wid)return; setWorkspaceId(wid);
  const [b,k,h,d,a,i,c]=await Promise.all([
   supabase.from("workspace_branding").select("*").eq("workspace_id",wid).maybeSingle(), supabase.from("workspace_api_keys").select("id,name,key_prefix,last_used_at,revoked_at,created_at").eq("workspace_id",wid).order("created_at",{ascending:false}),
   supabase.from("workspace_webhooks").select("*").eq("workspace_id",wid).order("created_at",{ascending:false}), supabase.from("workspace_webhook_deliveries").select("*,workspace_webhooks!inner(workspace_id,url)").eq("workspace_webhooks.workspace_id",wid).order("created_at",{ascending:false}).limit(30),
   supabase.from("workspace_audit_logs").select("*").eq("workspace_id",wid).order("created_at",{ascending:false}).limit(100), supabase.from("invoices").select("*").eq("user_id",profile?.user_id), supabase.from("clients").select("*").eq("user_id",profile?.user_id)
  ]); if(b.data)setBranding({...DEFAULT_BRANDING,...b.data}); setApiKeys(k.data||[]);setHooks(h.data||[]);setDeliveries(d.data||[]);setLogs(a.data||[]);setInvoices(i.data||[]);setClients(c.data||[]);
 },[isBusiness,profile?.user_id]); useEffect(()=>{void load()},[load]);
 const analytics=useMemo(()=>{const paid=invoices.filter(i=>i.status==="paid"), revenue=paid.reduce((s,i)=>s+Number(i.base_total??i.total??0),0), outstanding=invoices.filter(i=>i.status!=="paid").reduce((s,i)=>s+Number(i.base_total??i.total??0),0); const customer=new Map<string,number>(); const service=new Map<string,number>(); let tax=0; paid.forEach(i=>{customer.set(i.client_name,(customer.get(i.client_name)||0)+Number(i.total||0));tax+=Number(i.cgst||0)+Number(i.sgst||0)+Number(i.igst||0);(i.items||[]).forEach((x:any)=>service.set(x.description,(service.get(x.description)||0)+Number(x.qty||0)*Number(x.rate||0)))}); return {revenue,outstanding,tax,conversion:invoices.length?Math.round(paid.length/invoices.length*100):0,clv:clients.length?revenue/clients.length:0,top:[...customer].sort((a,b)=>b[1]-a[1]).slice(0,5),services:[...service].sort((a,b)=>b[1]-a[1]).slice(0,5)}},[invoices,clients]);
 async function saveBranding(){const {error}=await supabase.from("workspace_branding").upsert({...branding,workspace_id:workspaceId,updated_by:(await supabase.auth.getUser()).data.user?.id,updated_at:new Date().toISOString()});setMessage(error?.message||"Branding saved. New invoices, PDFs and emails will use these settings.")}
 async function createKey(){const name=prompt("API key name","Production integration");if(!name)return;const {data,error}=await supabase.rpc("create_workspace_api_key",{p_name:name});if(error)setMessage(error.message);else{setNewKey(data.api_key);setMessage("Copy this key now. It will never be shown again.");await load()}}
 async function revokeKey(id:string){if(!confirm("Revoke this API key?"))return;await supabase.rpc("revoke_workspace_api_key",{p_id:id});await load()}
 async function createHook(){if(!hookUrl.startsWith("https://")){setMessage("Webhook URL must start with https://");return} const secret="whsec_"+crypto.randomUUID().split("-").join("")+crypto.randomUUID().split("-").join("");const {error}=await supabase.from("workspace_webhooks").insert({workspace_id:workspaceId,url:hookUrl,events:hookEvents,signing_secret:secret});setMessage(error?.message||`Webhook created. Signing secret: ${secret}`);if(!error){setHookUrl("");await load()}}
 async function retry(id:string){const {data,error}=await supabase.functions.invoke("business-webhooks",{body:{action:"retry",deliveryId:id}});setMessage((data as any)?.error||error?.message||"Delivery retry completed.");await load()}
 if(!isBusiness)return <div className="mx-auto max-w-3xl card p-10 text-center"><p className="text-xs font-bold uppercase tracking-widest text-violet-600">Business workspace</p><h1 className="mt-3 text-3xl font-black">Unlock advanced operations</h1><p className="mt-3 text-slate-600">Custom branding, analytics, API keys, webhooks, audit logs and unlimited team seats are available on Business.</p><a href="/billing" className="btn-primary mt-7 inline-flex">Upgrade to Business</a></div>;
 const money=(n:number)=>new Intl.NumberFormat(undefined,{style:"currency",currency:profile?.currency||"USD"}).format(n);
 return <div className="mx-auto max-w-7xl space-y-6"><section className="rounded-[28px] bg-gradient-to-r from-slate-950 via-indigo-950 to-violet-900 p-8 text-white"><p className="text-xs font-bold uppercase tracking-[.25em] text-violet-300">Business command center</p><h1 className="mt-3 text-3xl font-black">Advanced workspace controls</h1><p className="mt-2 text-slate-300">Analytics, brand control and developer tools in one secure place.</p></section>{message&&<div className="rounded-2xl border border-violet-200 bg-violet-50 px-5 py-4 text-violet-800">{message}</div>}
 <div className="flex gap-2 overflow-x-auto pb-1">{(["analytics","branding","api","webhooks","audit"] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-4 py-2.5 text-sm font-bold capitalize ${tab===t?"bg-violet-600 text-white":"bg-white text-slate-600 border"}`}>{t}</button>)}</div>
 {tab==="analytics"&&<div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Revenue",money(analytics.revenue)],["Outstanding",money(analytics.outstanding)],["Tax collected",money(analytics.tax)],["Invoice conversion",analytics.conversion+"%"],["Customer LTV",money(analytics.clv)]].map(x=><div className="card p-5" key={x[0]}><p className="text-sm text-slate-500">{x[0]}</p><p className="mt-2 text-2xl font-black">{x[1]}</p></div>)}</div><div className="grid gap-6 lg:grid-cols-2"><Rank title="Top customers" rows={analytics.top} money={money}/><Rank title="Best services" rows={analytics.services} money={money}/></div></div>}
 {tab==="branding"&&profile&&<BrandStudio value={branding} onChange={setBranding} onSave={()=>void saveBranding()} profile={profile} workspaceId={workspaceId}/>} 
 {tab==="api"&&<div className="space-y-6"><div className="card p-6"><div className="flex justify-between gap-4"><div><h2 className="text-2xl font-black">API keys</h2><p className="text-slate-500">100 requests/minute per key. Store keys only on your server.</p></div><button className="btn-primary" onClick={()=>void createKey()}>Generate key</button></div>{newKey&&<div className="mt-5 rounded-xl bg-slate-950 p-4 font-mono text-sm text-emerald-300 break-all">{newKey}</div>}<div className="mt-5 divide-y">{apiKeys.map(k=><div className="flex items-center justify-between py-4" key={k.id}><div><b>{k.name}</b><p className="font-mono text-sm text-slate-500">{k.key_prefix}••••</p></div><button disabled={!!k.revoked_at} className="rounded-xl border px-4 py-2 text-sm font-bold disabled:opacity-40" onClick={()=>void revokeKey(k.id)}>{k.revoked_at?"Revoked":"Revoke"}</button></div>)}</div></div><div className="card p-6"><h3 className="text-xl font-black">Quick documentation</h3><pre className="mt-4 overflow-x-auto rounded-xl bg-slate-950 p-5 text-sm text-slate-200">{`Authorization: Bearer rvx_live_...\n\nGET /functions/v1/business-api/invoices\nGET /functions/v1/business-api/clients\nGET /functions/v1/business-api/invoices/{id}`}</pre></div></div>}
 {tab==="webhooks"&&<div className="space-y-6"><div className="card p-6"><h2 className="text-2xl font-black">Create webhook</h2><input className="input mt-4" placeholder="https://example.com/webhooks/rivox" value={hookUrl} onChange={e=>setHookUrl(e.target.value)}/><div className="mt-4 flex flex-wrap gap-2">{events.map(e=><label key={e} className={`rounded-full border px-3 py-2 text-sm ${hookEvents.includes(e)?"bg-violet-50 border-violet-300":""}`}><input className="mr-2" type="checkbox" checked={hookEvents.includes(e)} onChange={()=>setHookEvents(hookEvents.includes(e)?hookEvents.filter(x=>x!==e):[...hookEvents,e])}/>{e}</label>)}</div><button className="btn-primary mt-5" onClick={()=>void createHook()}>Create webhook</button></div><div className="card overflow-hidden"><div className="border-b p-5"><h3 className="text-xl font-black">Endpoints & delivery logs</h3></div>{hooks.map(h=><div className="border-b p-5" key={h.id}><b>{h.url}</b><p className="mt-1 text-sm text-slate-500">{h.events.join(", ")}</p></div>)}{deliveries.map(d=><div className="flex items-center justify-between gap-3 border-b p-5" key={d.id}><div><b>{d.event_type}</b><p className="text-sm text-slate-500">{d.status} · {d.attempts} attempts · {new Date(d.created_at).toLocaleString()}</p></div>{d.status!=="delivered"&&<button className="btn-secondary" onClick={()=>void retry(d.id)}>Retry</button>}</div>)}</div></div>}
 {tab==="audit"&&<div className="card overflow-hidden"><div className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-black">Audit logs</h2><p className="text-slate-500">Immutable workspace activity history.</p></div><input className="input sm:!w-72" placeholder="Filter action or email" value={filter} onChange={e=>setFilter(e.target.value)}/></div><div className="divide-y">{logs.filter(l=>`${l.action} ${l.actor_email||""}`.toLowerCase().includes(filter.toLowerCase())).map(l=><div className="p-5" key={l.id}><div className="flex justify-between gap-3"><b>{l.action.replaceAll("."," ")}</b><span className="text-xs text-slate-400">{new Date(l.created_at).toLocaleString()}</span></div><p className="mt-1 text-sm text-slate-500">{l.actor_email||"System"} · {l.entity_type||"workspace"}</p></div>)}</div></div>}</div>
}
function Rank({title,rows,money}:{title:string,rows:[string,number][],money:(n:number)=>string}){return <div className="card p-6"><h3 className="text-xl font-black">{title}</h3><div className="mt-4 space-y-3">{rows.length?rows.map(([n,v],i)=><div className="flex justify-between rounded-xl bg-slate-50 p-4" key={n}><span><b className="mr-3 text-violet-600">#{i+1}</b>{n}</span><b>{money(v)}</b></div>):<p className="text-slate-500">No paid invoice data yet.</p>}</div></div>}
