import { useState } from "react";
import { supabase } from "../lib/supabase";
import type { Profile } from "../lib/types";
import { brandingFont, type BrandTemplate, type WorkspaceBranding } from "../lib/branding";

const templates:{id:BrandTemplate;name:string;description:string}[]=[
 {id:"modern",name:"Modern",description:"Clean SaaS layout"},{id:"executive",name:"Executive",description:"Premium dark header"},{id:"minimal",name:"Minimal",description:"Quiet and spacious"},{id:"corporate",name:"Corporate",description:"Formal business style"},{id:"luxury",name:"Luxury",description:"Elegant studio design"},
];

export default function BrandStudio({value,onChange,onSave,profile}:{value:WorkspaceBranding;onChange:(v:WorkspaceBranding)=>void;onSave:()=>void;profile:Profile}){
 const [uploading,setUploading]=useState(""); const set=<K extends keyof WorkspaceBranding>(key:K,val:WorkspaceBranding[K])=>onChange({...value,[key]:val});
 async function upload(kind:"logo_url"|"signature_url"|"stamp_url",file?:File){if(!file)return;setUploading(kind);const ext=file.name.split(".").pop()?.toLowerCase()||"png";const path=`${profile.user_id}/${kind}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from("brand-assets").upload(path,file,{contentType:file.type,upsert:false});if(!error){const {data}=supabase.storage.from("brand-assets").getPublicUrl(path);set(kind,data.publicUrl)}setUploading("")}
 const header=value.pdf_template==="executive"?"bg-slate-950 text-white":value.pdf_template==="luxury"?"bg-stone-950 text-amber-100":value.pdf_template==="corporate"?"border-t-8 bg-slate-50":"bg-white";
 return <div className="space-y-6"><div className="grid gap-6 xl:grid-cols-[1fr_440px]"><div className="space-y-6">
  <section className="card p-6"><h2 className="text-2xl font-black">Business Brand Studio</h2><p className="mt-1 text-slate-500">Choose a premium layout, then make every customer-facing invoice yours.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{templates.map(t=><button key={t.id} onClick={()=>set("pdf_template",t.id)} className={`rounded-2xl border p-4 text-left transition ${value.pdf_template===t.id?"border-violet-500 bg-violet-50 ring-2 ring-violet-100":"hover:border-slate-300"}`}><div className={`mb-3 h-16 rounded-xl ${t.id==="executive"?"bg-slate-900":t.id==="luxury"?"bg-gradient-to-r from-stone-950 to-amber-700":t.id==="corporate"?"bg-gradient-to-b from-blue-700 to-blue-700/20":t.id==="minimal"?"border bg-white":"bg-gradient-to-r from-violet-600 to-indigo-500"}`}/><b>{t.name}</b><p className="text-xs text-slate-500">{t.description}</p></button>)}</div></section>
  <section className="card p-6"><h3 className="text-xl font-black">Brand assets</h3><div className="mt-5 grid gap-5 md:grid-cols-3">{([['logo_url','Company logo'],['signature_url','Signature'],['stamp_url','Company stamp']] as const).map(([key,label])=><label key={key} className="rounded-2xl border border-dashed p-4 text-center"><span className="block text-sm font-bold">{label}</span>{value[key]?<img src={value[key]} className="mx-auto mt-3 h-16 max-w-full object-contain"/>:<div className="mx-auto mt-3 grid h-16 place-items-center rounded-xl bg-slate-50 text-xs text-slate-400">No image</div>}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" className="mt-3 block w-full text-xs" onChange={e=>void upload(key,e.target.files?.[0])}/><span className="mt-2 block text-xs text-slate-400">{uploading===key?"Uploading...":"PNG, JPG, WebP or SVG"}</span></label>)}</div></section>
  <section className="card p-6"><h3 className="text-xl font-black">Design controls</h3><div className="mt-5 grid gap-5 md:grid-cols-2"><Color label="Primary color" value={value.brand_color} set={v=>set("brand_color",v)}/><Color label="Accent color" value={value.accent_color} set={v=>set("accent_color",v)}/><Select label="Typography" value={value.font_family} options={["modern","classic","editorial"]} set={v=>set("font_family",v as WorkspaceBranding['font_family'])}/><Select label="Table style" value={value.table_style} options={["solid","soft","lines"]} set={v=>set("table_style",v as WorkspaceBranding['table_style'])}/><Field label="Document title" value={value.invoice_title} set={v=>set("invoice_title",v.toUpperCase().slice(0,30))}/><Field label="Background watermark" value={value.background_watermark} set={v=>set("background_watermark",v.slice(0,40))}/></div></section>
  <section className="card p-6"><h3 className="text-xl font-black">Customer message</h3><div className="mt-5 space-y-4"><Field label="Footer message" value={value.footer_text} set={v=>set("footer_text",v)}/><Area label="Payment instructions" value={value.payment_instructions} set={v=>set("payment_instructions",v)}/><Area label="Terms & conditions" value={value.terms_text} set={v=>set("terms_text",v)}/><Field label="Email footer" value={value.email_footer} set={v=>set("email_footer",v)}/></div><div className="mt-5 flex flex-wrap gap-5"><Check label="Show signature" checked={value.show_signature} set={v=>set("show_signature",v)}/><Check label="Show company stamp" checked={value.show_stamp} set={v=>set("show_stamp",v)}/><Check label="White-label customer documents" checked={value.remove_rivox_branding} set={v=>set("remove_rivox_branding",v)}/></div></section>
  <button className="btn-primary px-7" onClick={onSave}>Save Brand Studio</button>
 </div><div className="xl:sticky xl:top-24 xl:h-fit"><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-violet-600">Live preview</p><div className="overflow-hidden rounded-[24px] border bg-white shadow-xl" style={{fontFamily:brandingFont(value.font_family)}}><div className={`relative p-6 ${header}`} style={value.pdf_template==="corporate"?{borderTopColor:value.brand_color}:{}}>{value.background_watermark&&<span className="absolute inset-0 grid place-items-center text-4xl font-black opacity-[.04]">{value.background_watermark}</span>}<div className="relative flex justify-between gap-4"> <div className="flex gap-3">{value.logo_url?<img src={value.logo_url} className="h-14 w-14 rounded-lg object-contain bg-white"/>:<div className="h-14 w-14 rounded-lg" style={{background:value.brand_color}}/>}<div><b className="text-lg">{profile.business_name||"Your Business"}</b><p className="text-xs opacity-70">{profile.email}</p></div></div><div className="text-right"><span className="rounded-lg px-3 py-1 text-xs font-black text-white" style={{background:value.brand_color}}>{value.invoice_title||"INVOICE"}</span><p className="mt-2 text-sm font-bold">INV-001</p></div></div></div><div className="p-6"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">Bill to</p><b>Example Customer</b><div className="mt-5 overflow-hidden rounded-xl"><div className="grid grid-cols-[1fr_auto] gap-3 p-3 text-xs font-bold" style={value.table_style==="solid"?{background:value.brand_color,color:"white"}:value.table_style==="soft"?{background:value.brand_color+"18",color:value.brand_color}:{borderBottom:`2px solid ${value.brand_color}`}}><span>Service</span><span>Amount</span></div><div className="grid grid-cols-[1fr_auto] p-3 text-sm"><span>Professional service</span><b>$1,250.00</b></div></div><div className="ml-auto mt-4 w-52 border-t pt-3"><div className="flex justify-between text-sm"><span>Total</span><b style={{color:value.brand_color}}>$1,250.00</b></div></div>{value.payment_instructions&&<div className="mt-5 rounded-xl bg-slate-50 p-3 text-xs"><b>Payment instructions</b><p>{value.payment_instructions}</p></div>}<div className="mt-8 text-center text-sm font-bold" style={{color:value.accent_color}}>{value.footer_text}</div>{(value.show_signature&&value.signature_url||value.show_stamp&&value.stamp_url)&&<div className="mt-5 flex justify-end gap-3">{value.show_signature&&value.signature_url&&<img src={value.signature_url} className="h-12 object-contain"/>}{value.show_stamp&&value.stamp_url&&<img src={value.stamp_url} className="h-12 object-contain"/>}</div>}{!value.remove_rivox_branding&&<p className="mt-4 text-center text-[10px] text-slate-400">Created with Rivox</p>}</div></div></div></div></div>
}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label><span className="mb-2 block text-sm font-bold">{label}</span><input className="input" value={value||""} onChange={e=>set(e.target.value)}/></label>}
function Area({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label><span className="mb-2 block text-sm font-bold">{label}</span><textarea className="input min-h-24" value={value||""} onChange={e=>set(e.target.value)}/></label>}
function Color({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label><span className="mb-2 block text-sm font-bold">{label}</span><div className="flex gap-2"><input type="color" className="h-12 w-16 rounded-lg border" value={value} onChange={e=>set(e.target.value)}/><input className="input" value={value} onChange={e=>set(e.target.value)}/></div></label>}
function Select({label,value,options,set}:{label:string;value:string;options:string[];set:(v:string)=>void}){return <label><span className="mb-2 block text-sm font-bold">{label}</span><select className="input capitalize" value={value} onChange={e=>set(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Check({label,checked,set}:{label:string;checked:boolean;set:(v:boolean)=>void}){return <label className="flex items-center gap-2 font-semibold"><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/>{label}</label>}
