export interface CountryCatalogEntry {
  name: string;
  iso2: string;
  callingCode: string;
  currency: string;
  symbol: string;
  decimals: number;
  timezone: string;
  dateFormat: string;
  locale: string;
}

export const COUNTRY_CATALOG: CountryCatalogEntry[] = [
  {
    "name": "Afghanistan",
    "iso2": "AF",
    "callingCode": "+93",
    "currency": "AFA",
    "symbol": "AFA",
    "decimals": 2,
    "timezone": "Asia/Kabul",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AF"
  },
  {
    "name": "Albania",
    "iso2": "AL",
    "callingCode": "+355",
    "currency": "ALK",
    "symbol": "ALK",
    "decimals": 2,
    "timezone": "Europe/Tirane",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AL"
  },
  {
    "name": "Algeria",
    "iso2": "DZ",
    "callingCode": "+213",
    "currency": "DZD",
    "symbol": "DZD",
    "decimals": 2,
    "timezone": "Africa/Algiers",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-DZ"
  },
  {
    "name": "American Samoa",
    "iso2": "AS",
    "callingCode": "+1",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "Pacific/Pago_Pago",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AS"
  },
  {
    "name": "Andorra",
    "iso2": "AD",
    "callingCode": "+376",
    "currency": "ESP",
    "symbol": "ESP",
    "decimals": 2,
    "timezone": "Europe/Andorra",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AD"
  },
  {
    "name": "Angola",
    "iso2": "AO",
    "callingCode": "+244",
    "currency": "AOK",
    "symbol": "AOK",
    "decimals": 2,
    "timezone": "Africa/Luanda",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AO"
  },
  {
    "name": "Anguilla",
    "iso2": "AI",
    "callingCode": "+1",
    "currency": "XCD",
    "symbol": "EC$",
    "decimals": 2,
    "timezone": "America/Anguilla",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AI"
  },
  {
    "name": "Antarctica",
    "iso2": "AQ",
    "callingCode": "",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "Antarctica/McMurdo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AQ"
  },
  {
    "name": "Antigua and Barbuda",
    "iso2": "AG",
    "callingCode": "+1",
    "currency": "XCD",
    "symbol": "EC$",
    "decimals": 2,
    "timezone": "America/Antigua",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AG"
  },
  {
    "name": "Argentina",
    "iso2": "AR",
    "callingCode": "+54",
    "currency": "ARM",
    "symbol": "ARM",
    "decimals": 2,
    "timezone": "America/Argentina/Buenos_Aires",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AR"
  },
  {
    "name": "Armenia",
    "iso2": "AM",
    "callingCode": "+374",
    "currency": "SUR",
    "symbol": "SUR",
    "decimals": 2,
    "timezone": "Asia/Yerevan",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AM"
  },
  {
    "name": "Aruba",
    "iso2": "AW",
    "callingCode": "+297",
    "currency": "ANG",
    "symbol": "ANG",
    "decimals": 2,
    "timezone": "America/Aruba",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AW"
  },
  {
    "name": "Australia",
    "iso2": "AU",
    "callingCode": "+61",
    "currency": "AUD",
    "symbol": "A$",
    "decimals": 2,
    "timezone": "Australia/Lord_Howe",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AU"
  },
  {
    "name": "Austria",
    "iso2": "AT",
    "callingCode": "+43",
    "currency": "ATS",
    "symbol": "ATS",
    "decimals": 2,
    "timezone": "Europe/Vienna",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AT"
  },
  {
    "name": "Azerbaijan",
    "iso2": "AZ",
    "callingCode": "+994",
    "currency": "SUR",
    "symbol": "SUR",
    "decimals": 2,
    "timezone": "Asia/Baku",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AZ"
  },
  {
    "name": "Bahamas",
    "iso2": "BS",
    "callingCode": "+1",
    "currency": "BSD",
    "symbol": "BSD",
    "decimals": 2,
    "timezone": "America/Nassau",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BS"
  },
  {
    "name": "Bahrain",
    "iso2": "BH",
    "callingCode": "+973",
    "currency": "BHD",
    "symbol": "BHD",
    "decimals": 3,
    "timezone": "Asia/Bahrain",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BH"
  },
  {
    "name": "Bangladesh",
    "iso2": "BD",
    "callingCode": "+880",
    "currency": "INR",
    "symbol": "₹",
    "decimals": 2,
    "timezone": "Asia/Dhaka",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BD"
  },
  {
    "name": "Barbados",
    "iso2": "BB",
    "callingCode": "+1",
    "currency": "XCD",
    "symbol": "EC$",
    "decimals": 2,
    "timezone": "America/Barbados",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BB"
  },
  {
    "name": "Belarus",
    "iso2": "BY",
    "callingCode": "+375",
    "currency": "SUR",
    "symbol": "SUR",
    "decimals": 2,
    "timezone": "Europe/Minsk",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BY"
  },
  {
    "name": "Belgium",
    "iso2": "BE",
    "callingCode": "+32",
    "currency": "NLG",
    "symbol": "NLG",
    "decimals": 2,
    "timezone": "Europe/Brussels",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BE"
  },
  {
    "name": "Belize",
    "iso2": "BZ",
    "callingCode": "+501",
    "currency": "BZD",
    "symbol": "BZD",
    "decimals": 2,
    "timezone": "America/Belize",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BZ"
  },
  {
    "name": "Benin",
    "iso2": "BJ",
    "callingCode": "+229",
    "currency": "XOF",
    "symbol": "F CFA",
    "decimals": 0,
    "timezone": "Africa/Porto-Novo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BJ"
  },
  {
    "name": "Bermuda",
    "iso2": "BM",
    "callingCode": "+1",
    "currency": "BMD",
    "symbol": "BMD",
    "decimals": 2,
    "timezone": "Atlantic/Bermuda",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BM"
  },
  {
    "name": "Bhutan",
    "iso2": "BT",
    "callingCode": "+975",
    "currency": "INR",
    "symbol": "₹",
    "decimals": 2,
    "timezone": "Asia/Thimphu",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BT"
  },
  {
    "name": "Bolivia",
    "iso2": "BO",
    "callingCode": "+591",
    "currency": "BOL",
    "symbol": "BOL",
    "decimals": 2,
    "timezone": "America/La_Paz",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BO"
  },
  {
    "name": "Bonaire, Sint Eustatius and Saba",
    "iso2": "BQ",
    "callingCode": "+599",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "America/Kralendijk",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BQ"
  },
  {
    "name": "Bosnia and Herzegovina",
    "iso2": "BA",
    "callingCode": "+387",
    "currency": "YUD",
    "symbol": "YUD",
    "decimals": 2,
    "timezone": "Europe/Sarajevo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BA"
  },
  {
    "name": "Botswana",
    "iso2": "BW",
    "callingCode": "+267",
    "currency": "ZAR",
    "symbol": "ZAR",
    "decimals": 2,
    "timezone": "Africa/Gaborone",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BW"
  },
  {
    "name": "Bouvet Island",
    "iso2": "BV",
    "callingCode": "",
    "currency": "NOK",
    "symbol": "NOK",
    "decimals": 2,
    "timezone": "UTC",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BV"
  },
  {
    "name": "Brazil",
    "iso2": "BR",
    "callingCode": "+55",
    "currency": "BRZ",
    "symbol": "BRZ",
    "decimals": 2,
    "timezone": "America/Noronha",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BR"
  },
  {
    "name": "British Indian Ocean Territory",
    "iso2": "IO",
    "callingCode": "+246",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "Indian/Chagos",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-IO"
  },
  {
    "name": "Brunei",
    "iso2": "BN",
    "callingCode": "+673",
    "currency": "MYR",
    "symbol": "MYR",
    "decimals": 2,
    "timezone": "Asia/Brunei",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BN"
  },
  {
    "name": "Bulgaria",
    "iso2": "BG",
    "callingCode": "+359",
    "currency": "BGO",
    "symbol": "BGO",
    "decimals": 2,
    "timezone": "Europe/Sofia",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BG"
  },
  {
    "name": "Burkina Faso",
    "iso2": "BF",
    "callingCode": "+226",
    "currency": "XOF",
    "symbol": "F CFA",
    "decimals": 0,
    "timezone": "Africa/Ouagadougou",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BF"
  },
  {
    "name": "Burundi",
    "iso2": "BI",
    "callingCode": "+257",
    "currency": "BIF",
    "symbol": "BIF",
    "decimals": 0,
    "timezone": "Africa/Bujumbura",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BI"
  },
  {
    "name": "Cabo Verde",
    "iso2": "CV",
    "callingCode": "+238",
    "currency": "PTE",
    "symbol": "PTE",
    "decimals": 2,
    "timezone": "Atlantic/Cape_Verde",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CV"
  },
  {
    "name": "Cambodia",
    "iso2": "KH",
    "callingCode": "+855",
    "currency": "KHR",
    "symbol": "KHR",
    "decimals": 2,
    "timezone": "Asia/Phnom_Penh",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-KH"
  },
  {
    "name": "Cameroon",
    "iso2": "CM",
    "callingCode": "+237",
    "currency": "XAF",
    "symbol": "FCFA",
    "decimals": 0,
    "timezone": "Africa/Douala",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CM"
  },
  {
    "name": "Canada",
    "iso2": "CA",
    "callingCode": "+1",
    "currency": "CAD",
    "symbol": "CA$",
    "decimals": 2,
    "timezone": "America/St_Johns",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CA"
  },
  {
    "name": "Cayman Islands",
    "iso2": "KY",
    "callingCode": "+1",
    "currency": "JMD",
    "symbol": "JMD",
    "decimals": 2,
    "timezone": "America/Cayman",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-KY"
  },
  {
    "name": "Central African Republic",
    "iso2": "CF",
    "callingCode": "+236",
    "currency": "XAF",
    "symbol": "FCFA",
    "decimals": 0,
    "timezone": "Africa/Bangui",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CF"
  },
  {
    "name": "Chad",
    "iso2": "TD",
    "callingCode": "+235",
    "currency": "XAF",
    "symbol": "FCFA",
    "decimals": 0,
    "timezone": "Africa/Ndjamena",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TD"
  },
  {
    "name": "Chile",
    "iso2": "CL",
    "callingCode": "+56",
    "currency": "CLE",
    "symbol": "CLE",
    "decimals": 2,
    "timezone": "America/Santiago",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CL"
  },
  {
    "name": "China",
    "iso2": "CN",
    "callingCode": "+86",
    "currency": "CNY",
    "symbol": "CN¥",
    "decimals": 2,
    "timezone": "Asia/Shanghai",
    "dateFormat": "YYYY/MM/DD",
    "locale": "en-CN"
  },
  {
    "name": "Christmas Island",
    "iso2": "CX",
    "callingCode": "+61",
    "currency": "AUD",
    "symbol": "A$",
    "decimals": 2,
    "timezone": "Indian/Christmas",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CX"
  },
  {
    "name": "Cocos (Keeling) Islands",
    "iso2": "CC",
    "callingCode": "+61",
    "currency": "AUD",
    "symbol": "A$",
    "decimals": 2,
    "timezone": "Indian/Cocos",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CC"
  },
  {
    "name": "Colombia",
    "iso2": "CO",
    "callingCode": "+57",
    "currency": "COP",
    "symbol": "COP",
    "decimals": 2,
    "timezone": "America/Bogota",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CO"
  },
  {
    "name": "Comoros",
    "iso2": "KM",
    "callingCode": "+269",
    "currency": "KMF",
    "symbol": "KMF",
    "decimals": 0,
    "timezone": "Indian/Comoro",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-KM"
  },
  {
    "name": "Congo",
    "iso2": "CG",
    "callingCode": "+242",
    "currency": "XAF",
    "symbol": "FCFA",
    "decimals": 0,
    "timezone": "Africa/Brazzaville",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CG"
  },
  {
    "name": "Congo, The Democratic Republic of the",
    "iso2": "CD",
    "callingCode": "+243",
    "currency": "ZRZ",
    "symbol": "ZRZ",
    "decimals": 2,
    "timezone": "Africa/Kinshasa",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CD"
  },
  {
    "name": "Cook Islands",
    "iso2": "CK",
    "callingCode": "+682",
    "currency": "NZD",
    "symbol": "NZ$",
    "decimals": 2,
    "timezone": "Pacific/Rarotonga",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CK"
  },
  {
    "name": "Costa Rica",
    "iso2": "CR",
    "callingCode": "+506",
    "currency": "CRC",
    "symbol": "CRC",
    "decimals": 2,
    "timezone": "America/Costa_Rica",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CR"
  },
  {
    "name": "Croatia",
    "iso2": "HR",
    "callingCode": "+385",
    "currency": "YUD",
    "symbol": "YUD",
    "decimals": 2,
    "timezone": "Europe/Zagreb",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-HR"
  },
  {
    "name": "Cuba",
    "iso2": "CU",
    "callingCode": "+53",
    "currency": "CUP",
    "symbol": "CUP",
    "decimals": 2,
    "timezone": "America/Havana",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CU"
  },
  {
    "name": "Curaçao",
    "iso2": "CW",
    "callingCode": "+599",
    "currency": "ANG",
    "symbol": "ANG",
    "decimals": 2,
    "timezone": "America/Curacao",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CW"
  },
  {
    "name": "Cyprus",
    "iso2": "CY",
    "callingCode": "+357",
    "currency": "CYP",
    "symbol": "CYP",
    "decimals": 2,
    "timezone": "Asia/Nicosia",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CY"
  },
  {
    "name": "Czech Republic",
    "iso2": "CZ",
    "callingCode": "+420",
    "currency": "CSK",
    "symbol": "CSK",
    "decimals": 2,
    "timezone": "Europe/Prague",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CZ"
  },
  {
    "name": "Côte d'Ivoire",
    "iso2": "CI",
    "callingCode": "+225",
    "currency": "XOF",
    "symbol": "F CFA",
    "decimals": 0,
    "timezone": "Africa/Abidjan",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CI"
  },
  {
    "name": "Denmark",
    "iso2": "DK",
    "callingCode": "+45",
    "currency": "DKK",
    "symbol": "DKK",
    "decimals": 2,
    "timezone": "Europe/Copenhagen",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-DK"
  },
  {
    "name": "Djibouti",
    "iso2": "DJ",
    "callingCode": "+253",
    "currency": "DJF",
    "symbol": "DJF",
    "decimals": 0,
    "timezone": "Africa/Djibouti",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-DJ"
  },
  {
    "name": "Dominica",
    "iso2": "DM",
    "callingCode": "+1",
    "currency": "XCD",
    "symbol": "EC$",
    "decimals": 2,
    "timezone": "America/Dominica",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-DM"
  },
  {
    "name": "Dominican Republic",
    "iso2": "DO",
    "callingCode": "+1",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "America/Santo_Domingo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-DO"
  },
  {
    "name": "Ecuador",
    "iso2": "EC",
    "callingCode": "+593",
    "currency": "ECS",
    "symbol": "ECS",
    "decimals": 2,
    "timezone": "America/Guayaquil",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-EC"
  },
  {
    "name": "Egypt",
    "iso2": "EG",
    "callingCode": "+20",
    "currency": "EGP",
    "symbol": "EGP",
    "decimals": 2,
    "timezone": "Africa/Cairo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-EG"
  },
  {
    "name": "El Salvador",
    "iso2": "SV",
    "callingCode": "+503",
    "currency": "SVC",
    "symbol": "SVC",
    "decimals": 2,
    "timezone": "America/El_Salvador",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SV"
  },
  {
    "name": "Equatorial Guinea",
    "iso2": "GQ",
    "callingCode": "+240",
    "currency": "GQE",
    "symbol": "GQE",
    "decimals": 2,
    "timezone": "Africa/Malabo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GQ"
  },
  {
    "name": "Eritrea",
    "iso2": "ER",
    "callingCode": "+291",
    "currency": "ETB",
    "symbol": "ETB",
    "decimals": 2,
    "timezone": "Africa/Asmara",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-ER"
  },
  {
    "name": "Estonia",
    "iso2": "EE",
    "callingCode": "+372",
    "currency": "SUR",
    "symbol": "SUR",
    "decimals": 2,
    "timezone": "Europe/Tallinn",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-EE"
  },
  {
    "name": "Eswatini",
    "iso2": "SZ",
    "callingCode": "+268",
    "currency": "SZL",
    "symbol": "SZL",
    "decimals": 2,
    "timezone": "Africa/Mbabane",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SZ"
  },
  {
    "name": "Ethiopia",
    "iso2": "ET",
    "callingCode": "+251",
    "currency": "ETB",
    "symbol": "ETB",
    "decimals": 2,
    "timezone": "Africa/Addis_Ababa",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-ET"
  },
  {
    "name": "Falkland Islands (Malvinas)",
    "iso2": "FK",
    "callingCode": "+500",
    "currency": "FKP",
    "symbol": "FKP",
    "decimals": 2,
    "timezone": "Atlantic/Stanley",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-FK"
  },
  {
    "name": "Faroe Islands",
    "iso2": "FO",
    "callingCode": "+298",
    "currency": "DKK",
    "symbol": "DKK",
    "decimals": 2,
    "timezone": "Atlantic/Faroe",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-FO"
  },
  {
    "name": "Fiji",
    "iso2": "FJ",
    "callingCode": "+679",
    "currency": "FJD",
    "symbol": "FJD",
    "decimals": 2,
    "timezone": "Pacific/Fiji",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-FJ"
  },
  {
    "name": "Finland",
    "iso2": "FI",
    "callingCode": "+358",
    "currency": "FIM",
    "symbol": "FIM",
    "decimals": 2,
    "timezone": "Europe/Helsinki",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-FI"
  },
  {
    "name": "France",
    "iso2": "FR",
    "callingCode": "+33",
    "currency": "FRF",
    "symbol": "FRF",
    "decimals": 2,
    "timezone": "Europe/Paris",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-FR"
  },
  {
    "name": "French Guiana",
    "iso2": "GF",
    "callingCode": "+594",
    "currency": "FRF",
    "symbol": "FRF",
    "decimals": 2,
    "timezone": "America/Cayenne",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GF"
  },
  {
    "name": "French Polynesia",
    "iso2": "PF",
    "callingCode": "+689",
    "currency": "XPF",
    "symbol": "CFPF",
    "decimals": 2,
    "timezone": "Pacific/Tahiti",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PF"
  },
  {
    "name": "French Southern Territories",
    "iso2": "TF",
    "callingCode": "",
    "currency": "EUR",
    "symbol": "€",
    "decimals": 2,
    "timezone": "Indian/Kerguelen",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TF"
  },
  {
    "name": "Gabon",
    "iso2": "GA",
    "callingCode": "+241",
    "currency": "XAF",
    "symbol": "FCFA",
    "decimals": 0,
    "timezone": "Africa/Libreville",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GA"
  },
  {
    "name": "Gambia",
    "iso2": "GM",
    "callingCode": "+220",
    "currency": "GMD",
    "symbol": "GMD",
    "decimals": 2,
    "timezone": "Africa/Banjul",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GM"
  },
  {
    "name": "Georgia",
    "iso2": "GE",
    "callingCode": "+995",
    "currency": "SUR",
    "symbol": "SUR",
    "decimals": 2,
    "timezone": "Asia/Tbilisi",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GE"
  },
  {
    "name": "Germany",
    "iso2": "DE",
    "callingCode": "+49",
    "currency": "DEM",
    "symbol": "DEM",
    "decimals": 2,
    "timezone": "Europe/Berlin",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-DE"
  },
  {
    "name": "Ghana",
    "iso2": "GH",
    "callingCode": "+233",
    "currency": "GHC",
    "symbol": "GHC",
    "decimals": 2,
    "timezone": "Africa/Accra",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GH"
  },
  {
    "name": "Gibraltar",
    "iso2": "GI",
    "callingCode": "+350",
    "currency": "GIP",
    "symbol": "GIP",
    "decimals": 2,
    "timezone": "Europe/Gibraltar",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GI"
  },
  {
    "name": "Greece",
    "iso2": "GR",
    "callingCode": "+30",
    "currency": "GRD",
    "symbol": "GRD",
    "decimals": 2,
    "timezone": "Europe/Athens",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GR"
  },
  {
    "name": "Greenland",
    "iso2": "GL",
    "callingCode": "+299",
    "currency": "DKK",
    "symbol": "DKK",
    "decimals": 2,
    "timezone": "America/Nuuk",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GL"
  },
  {
    "name": "Grenada",
    "iso2": "GD",
    "callingCode": "+1",
    "currency": "XCD",
    "symbol": "EC$",
    "decimals": 2,
    "timezone": "America/Grenada",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GD"
  },
  {
    "name": "Guadeloupe",
    "iso2": "GP",
    "callingCode": "+590",
    "currency": "FRF",
    "symbol": "FRF",
    "decimals": 2,
    "timezone": "America/Guadeloupe",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GP"
  },
  {
    "name": "Guam",
    "iso2": "GU",
    "callingCode": "+1",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "Pacific/Guam",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GU"
  },
  {
    "name": "Guatemala",
    "iso2": "GT",
    "callingCode": "+502",
    "currency": "GTQ",
    "symbol": "GTQ",
    "decimals": 2,
    "timezone": "America/Guatemala",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GT"
  },
  {
    "name": "Guernsey",
    "iso2": "GG",
    "callingCode": "+44",
    "currency": "GBP",
    "symbol": "£",
    "decimals": 2,
    "timezone": "Europe/Guernsey",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GG"
  },
  {
    "name": "Guinea",
    "iso2": "GN",
    "callingCode": "+224",
    "currency": "GNS",
    "symbol": "GNS",
    "decimals": 2,
    "timezone": "Africa/Conakry",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GN"
  },
  {
    "name": "Guinea-Bissau",
    "iso2": "GW",
    "callingCode": "+245",
    "currency": "GWE",
    "symbol": "GWE",
    "decimals": 2,
    "timezone": "Africa/Bissau",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GW"
  },
  {
    "name": "Guyana",
    "iso2": "GY",
    "callingCode": "+592",
    "currency": "GYD",
    "symbol": "GYD",
    "decimals": 2,
    "timezone": "America/Guyana",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GY"
  },
  {
    "name": "Haiti",
    "iso2": "HT",
    "callingCode": "+509",
    "currency": "HTG",
    "symbol": "HTG",
    "decimals": 2,
    "timezone": "America/Port-au-Prince",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-HT"
  },
  {
    "name": "Heard Island and McDonald Islands",
    "iso2": "HM",
    "callingCode": "",
    "currency": "AUD",
    "symbol": "A$",
    "decimals": 2,
    "timezone": "UTC",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-HM"
  },
  {
    "name": "Holy See (Vatican City State)",
    "iso2": "VA",
    "callingCode": "+39",
    "currency": "ITL",
    "symbol": "ITL",
    "decimals": 2,
    "timezone": "Europe/Vatican",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-VA"
  },
  {
    "name": "Honduras",
    "iso2": "HN",
    "callingCode": "+504",
    "currency": "HNL",
    "symbol": "HNL",
    "decimals": 2,
    "timezone": "America/Tegucigalpa",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-HN"
  },
  {
    "name": "Hong Kong",
    "iso2": "HK",
    "callingCode": "+852",
    "currency": "HKD",
    "symbol": "HK$",
    "decimals": 2,
    "timezone": "Asia/Hong_Kong",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-HK"
  },
  {
    "name": "Hungary",
    "iso2": "HU",
    "callingCode": "+36",
    "currency": "HUF",
    "symbol": "HUF",
    "decimals": 2,
    "timezone": "Europe/Budapest",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-HU"
  },
  {
    "name": "Iceland",
    "iso2": "IS",
    "callingCode": "+354",
    "currency": "DKK",
    "symbol": "DKK",
    "decimals": 2,
    "timezone": "Atlantic/Reykjavik",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-IS"
  },
  {
    "name": "India",
    "iso2": "IN",
    "callingCode": "+91",
    "currency": "INR",
    "symbol": "₹",
    "decimals": 2,
    "timezone": "Asia/Kolkata",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-IN"
  },
  {
    "name": "Indonesia",
    "iso2": "ID",
    "callingCode": "+62",
    "currency": "IDR",
    "symbol": "IDR",
    "decimals": 2,
    "timezone": "Asia/Jakarta",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-ID"
  },
  {
    "name": "Iran",
    "iso2": "IR",
    "callingCode": "+98",
    "currency": "IRR",
    "symbol": "IRR",
    "decimals": 2,
    "timezone": "Asia/Tehran",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-IR"
  },
  {
    "name": "Iraq",
    "iso2": "IQ",
    "callingCode": "+964",
    "currency": "EGP",
    "symbol": "EGP",
    "decimals": 2,
    "timezone": "Asia/Baghdad",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-IQ"
  },
  {
    "name": "Ireland",
    "iso2": "IE",
    "callingCode": "+353",
    "currency": "GBP",
    "symbol": "£",
    "decimals": 2,
    "timezone": "Europe/Dublin",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-IE"
  },
  {
    "name": "Isle of Man",
    "iso2": "IM",
    "callingCode": "+44",
    "currency": "GBP",
    "symbol": "£",
    "decimals": 2,
    "timezone": "Europe/Isle_of_Man",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-IM"
  },
  {
    "name": "Israel",
    "iso2": "IL",
    "callingCode": "+972",
    "currency": "ILP",
    "symbol": "ILP",
    "decimals": 2,
    "timezone": "Asia/Jerusalem",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-IL"
  },
  {
    "name": "Italy",
    "iso2": "IT",
    "callingCode": "+39",
    "currency": "ITL",
    "symbol": "ITL",
    "decimals": 2,
    "timezone": "Europe/Rome",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-IT"
  },
  {
    "name": "Jamaica",
    "iso2": "JM",
    "callingCode": "+1",
    "currency": "JMD",
    "symbol": "JMD",
    "decimals": 2,
    "timezone": "America/Jamaica",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-JM"
  },
  {
    "name": "Japan",
    "iso2": "JP",
    "callingCode": "+81",
    "currency": "JPY",
    "symbol": "¥",
    "decimals": 0,
    "timezone": "Asia/Tokyo",
    "dateFormat": "YYYY/MM/DD",
    "locale": "en-JP"
  },
  {
    "name": "Jersey",
    "iso2": "JE",
    "callingCode": "+44",
    "currency": "GBP",
    "symbol": "£",
    "decimals": 2,
    "timezone": "Europe/Jersey",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-JE"
  },
  {
    "name": "Jordan",
    "iso2": "JO",
    "callingCode": "+962",
    "currency": "JOD",
    "symbol": "JOD",
    "decimals": 3,
    "timezone": "Asia/Amman",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-JO"
  },
  {
    "name": "Kazakhstan",
    "iso2": "KZ",
    "callingCode": "+7",
    "currency": "KZT",
    "symbol": "KZT",
    "decimals": 2,
    "timezone": "Asia/Almaty",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-KZ"
  },
  {
    "name": "Kenya",
    "iso2": "KE",
    "callingCode": "+254",
    "currency": "KES",
    "symbol": "KES",
    "decimals": 2,
    "timezone": "Africa/Nairobi",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-KE"
  },
  {
    "name": "Kiribati",
    "iso2": "KI",
    "callingCode": "+686",
    "currency": "AUD",
    "symbol": "A$",
    "decimals": 2,
    "timezone": "Pacific/Tarawa",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-KI"
  },
  {
    "name": "Kuwait",
    "iso2": "KW",
    "callingCode": "+965",
    "currency": "KWD",
    "symbol": "KWD",
    "decimals": 3,
    "timezone": "Asia/Kuwait",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-KW"
  },
  {
    "name": "Kyrgyzstan",
    "iso2": "KG",
    "callingCode": "+996",
    "currency": "SUR",
    "symbol": "SUR",
    "decimals": 2,
    "timezone": "Asia/Bishkek",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-KG"
  },
  {
    "name": "Laos",
    "iso2": "LA",
    "callingCode": "+856",
    "currency": "LAK",
    "symbol": "LAK",
    "decimals": 2,
    "timezone": "Asia/Vientiane",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-LA"
  },
  {
    "name": "Latvia",
    "iso2": "LV",
    "callingCode": "+371",
    "currency": "SUR",
    "symbol": "SUR",
    "decimals": 2,
    "timezone": "Europe/Riga",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-LV"
  },
  {
    "name": "Lebanon",
    "iso2": "LB",
    "callingCode": "+961",
    "currency": "LBP",
    "symbol": "LBP",
    "decimals": 2,
    "timezone": "Asia/Beirut",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-LB"
  },
  {
    "name": "Lesotho",
    "iso2": "LS",
    "callingCode": "+266",
    "currency": "ZAR",
    "symbol": "ZAR",
    "decimals": 2,
    "timezone": "Africa/Maseru",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-LS"
  },
  {
    "name": "Liberia",
    "iso2": "LR",
    "callingCode": "+231",
    "currency": "LRD",
    "symbol": "LRD",
    "decimals": 2,
    "timezone": "Africa/Monrovia",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-LR"
  },
  {
    "name": "Libya",
    "iso2": "LY",
    "callingCode": "+218",
    "currency": "LYD",
    "symbol": "LYD",
    "decimals": 3,
    "timezone": "Africa/Tripoli",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-LY"
  },
  {
    "name": "Liechtenstein",
    "iso2": "LI",
    "callingCode": "+423",
    "currency": "CHF",
    "symbol": "CHF",
    "decimals": 2,
    "timezone": "Europe/Vaduz",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-LI"
  },
  {
    "name": "Lithuania",
    "iso2": "LT",
    "callingCode": "+370",
    "currency": "SUR",
    "symbol": "SUR",
    "decimals": 2,
    "timezone": "Europe/Vilnius",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-LT"
  },
  {
    "name": "Luxembourg",
    "iso2": "LU",
    "callingCode": "+352",
    "currency": "LUF",
    "symbol": "LUF",
    "decimals": 2,
    "timezone": "Europe/Luxembourg",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-LU"
  },
  {
    "name": "Macao",
    "iso2": "MO",
    "callingCode": "+853",
    "currency": "MOP",
    "symbol": "MOP",
    "decimals": 2,
    "timezone": "Asia/Macau",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MO"
  },
  {
    "name": "Madagascar",
    "iso2": "MG",
    "callingCode": "+261",
    "currency": "MGF",
    "symbol": "MGF",
    "decimals": 2,
    "timezone": "Indian/Antananarivo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MG"
  },
  {
    "name": "Malawi",
    "iso2": "MW",
    "callingCode": "+265",
    "currency": "MWK",
    "symbol": "MWK",
    "decimals": 2,
    "timezone": "Africa/Blantyre",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MW"
  },
  {
    "name": "Malaysia",
    "iso2": "MY",
    "callingCode": "+60",
    "currency": "MYR",
    "symbol": "MYR",
    "decimals": 2,
    "timezone": "Asia/Kuala_Lumpur",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MY"
  },
  {
    "name": "Maldives",
    "iso2": "MV",
    "callingCode": "+960",
    "currency": "MVP",
    "symbol": "MVP",
    "decimals": 2,
    "timezone": "Indian/Maldives",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MV"
  },
  {
    "name": "Mali",
    "iso2": "ML",
    "callingCode": "+223",
    "currency": "XOF",
    "symbol": "F CFA",
    "decimals": 0,
    "timezone": "Africa/Bamako",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-ML"
  },
  {
    "name": "Malta",
    "iso2": "MT",
    "callingCode": "+356",
    "currency": "MTP",
    "symbol": "MTP",
    "decimals": 2,
    "timezone": "Europe/Malta",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MT"
  },
  {
    "name": "Marshall Islands",
    "iso2": "MH",
    "callingCode": "+692",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "Pacific/Majuro",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MH"
  },
  {
    "name": "Martinique",
    "iso2": "MQ",
    "callingCode": "+596",
    "currency": "FRF",
    "symbol": "FRF",
    "decimals": 2,
    "timezone": "America/Martinique",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MQ"
  },
  {
    "name": "Mauritania",
    "iso2": "MR",
    "callingCode": "+222",
    "currency": "XOF",
    "symbol": "F CFA",
    "decimals": 0,
    "timezone": "Africa/Nouakchott",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MR"
  },
  {
    "name": "Mauritius",
    "iso2": "MU",
    "callingCode": "+230",
    "currency": "MUR",
    "symbol": "MUR",
    "decimals": 2,
    "timezone": "Indian/Mauritius",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MU"
  },
  {
    "name": "Mayotte",
    "iso2": "YT",
    "callingCode": "+262",
    "currency": "KMF",
    "symbol": "KMF",
    "decimals": 0,
    "timezone": "Indian/Mayotte",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-YT"
  },
  {
    "name": "Mexico",
    "iso2": "MX",
    "callingCode": "+52",
    "currency": "MXP",
    "symbol": "MXP",
    "decimals": 2,
    "timezone": "America/Mexico_City",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MX"
  },
  {
    "name": "Micronesia",
    "iso2": "FM",
    "callingCode": "+691",
    "currency": "JPY",
    "symbol": "¥",
    "decimals": 0,
    "timezone": "Pacific/Chuuk",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-FM"
  },
  {
    "name": "Moldova",
    "iso2": "MD",
    "callingCode": "+373",
    "currency": "MDC",
    "symbol": "MDC",
    "decimals": 2,
    "timezone": "Europe/Chisinau",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MD"
  },
  {
    "name": "Monaco",
    "iso2": "MC",
    "callingCode": "+377",
    "currency": "FRF",
    "symbol": "FRF",
    "decimals": 2,
    "timezone": "Europe/Monaco",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MC"
  },
  {
    "name": "Mongolia",
    "iso2": "MN",
    "callingCode": "+976",
    "currency": "MNT",
    "symbol": "MNT",
    "decimals": 2,
    "timezone": "Asia/Ulaanbaatar",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MN"
  },
  {
    "name": "Montenegro",
    "iso2": "ME",
    "callingCode": "+382",
    "currency": "YUM",
    "symbol": "YUM",
    "decimals": 2,
    "timezone": "Europe/Podgorica",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-ME"
  },
  {
    "name": "Montserrat",
    "iso2": "MS",
    "callingCode": "+1",
    "currency": "XCD",
    "symbol": "EC$",
    "decimals": 2,
    "timezone": "America/Montserrat",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MS"
  },
  {
    "name": "Morocco",
    "iso2": "MA",
    "callingCode": "+212",
    "currency": "MAF",
    "symbol": "MAF",
    "decimals": 2,
    "timezone": "Africa/Casablanca",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MA"
  },
  {
    "name": "Mozambique",
    "iso2": "MZ",
    "callingCode": "+258",
    "currency": "MZE",
    "symbol": "MZE",
    "decimals": 2,
    "timezone": "Africa/Maputo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MZ"
  },
  {
    "name": "Myanmar",
    "iso2": "MM",
    "callingCode": "+95",
    "currency": "BUK",
    "symbol": "BUK",
    "decimals": 2,
    "timezone": "Asia/Yangon",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MM"
  },
  {
    "name": "Namibia",
    "iso2": "NA",
    "callingCode": "+264",
    "currency": "ZAR",
    "symbol": "ZAR",
    "decimals": 2,
    "timezone": "Africa/Windhoek",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-NA"
  },
  {
    "name": "Nauru",
    "iso2": "NR",
    "callingCode": "+674",
    "currency": "AUD",
    "symbol": "A$",
    "decimals": 2,
    "timezone": "Pacific/Nauru",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-NR"
  },
  {
    "name": "Nepal",
    "iso2": "NP",
    "callingCode": "+977",
    "currency": "INR",
    "symbol": "₹",
    "decimals": 2,
    "timezone": "Asia/Kathmandu",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-NP"
  },
  {
    "name": "Netherlands",
    "iso2": "NL",
    "callingCode": "+31",
    "currency": "NLG",
    "symbol": "NLG",
    "decimals": 2,
    "timezone": "Europe/Amsterdam",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-NL"
  },
  {
    "name": "New Caledonia",
    "iso2": "NC",
    "callingCode": "+687",
    "currency": "XPF",
    "symbol": "CFPF",
    "decimals": 2,
    "timezone": "Pacific/Noumea",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-NC"
  },
  {
    "name": "New Zealand",
    "iso2": "NZ",
    "callingCode": "+64",
    "currency": "NZD",
    "symbol": "NZ$",
    "decimals": 2,
    "timezone": "Pacific/Auckland",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-NZ"
  },
  {
    "name": "Nicaragua",
    "iso2": "NI",
    "callingCode": "+505",
    "currency": "NIC",
    "symbol": "NIC",
    "decimals": 2,
    "timezone": "America/Managua",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-NI"
  },
  {
    "name": "Niger",
    "iso2": "NE",
    "callingCode": "+227",
    "currency": "XOF",
    "symbol": "F CFA",
    "decimals": 0,
    "timezone": "Africa/Niamey",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-NE"
  },
  {
    "name": "Nigeria",
    "iso2": "NG",
    "callingCode": "+234",
    "currency": "NGN",
    "symbol": "NGN",
    "decimals": 2,
    "timezone": "Africa/Lagos",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-NG"
  },
  {
    "name": "Niue",
    "iso2": "NU",
    "callingCode": "+683",
    "currency": "NZD",
    "symbol": "NZ$",
    "decimals": 2,
    "timezone": "Pacific/Niue",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-NU"
  },
  {
    "name": "Norfolk Island",
    "iso2": "NF",
    "callingCode": "+672",
    "currency": "AUD",
    "symbol": "A$",
    "decimals": 2,
    "timezone": "Pacific/Norfolk",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-NF"
  },
  {
    "name": "North Korea",
    "iso2": "KP",
    "callingCode": "+850",
    "currency": "KPW",
    "symbol": "KPW",
    "decimals": 2,
    "timezone": "Asia/Pyongyang",
    "dateFormat": "YYYY/MM/DD",
    "locale": "en-KP"
  },
  {
    "name": "North Macedonia",
    "iso2": "MK",
    "callingCode": "+389",
    "currency": "MKN",
    "symbol": "MKN",
    "decimals": 2,
    "timezone": "Europe/Skopje",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MK"
  },
  {
    "name": "Northern Mariana Islands",
    "iso2": "MP",
    "callingCode": "+1",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "Pacific/Saipan",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MP"
  },
  {
    "name": "Norway",
    "iso2": "NO",
    "callingCode": "+47",
    "currency": "SEK",
    "symbol": "SEK",
    "decimals": 2,
    "timezone": "Europe/Oslo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-NO"
  },
  {
    "name": "Oman",
    "iso2": "OM",
    "callingCode": "+968",
    "currency": "OMR",
    "symbol": "OMR",
    "decimals": 3,
    "timezone": "Asia/Muscat",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-OM"
  },
  {
    "name": "Pakistan",
    "iso2": "PK",
    "callingCode": "+92",
    "currency": "INR",
    "symbol": "₹",
    "decimals": 2,
    "timezone": "Asia/Karachi",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PK"
  },
  {
    "name": "Palau",
    "iso2": "PW",
    "callingCode": "+680",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "Pacific/Palau",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PW"
  },
  {
    "name": "Palestine",
    "iso2": "PS",
    "callingCode": "+970",
    "currency": "ILS",
    "symbol": "₪",
    "decimals": 2,
    "timezone": "Asia/Gaza",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PS"
  },
  {
    "name": "Panama",
    "iso2": "PA",
    "callingCode": "+507",
    "currency": "PAB",
    "symbol": "PAB",
    "decimals": 2,
    "timezone": "America/Panama",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PA"
  },
  {
    "name": "Papua New Guinea",
    "iso2": "PG",
    "callingCode": "+675",
    "currency": "AUD",
    "symbol": "A$",
    "decimals": 2,
    "timezone": "Pacific/Port_Moresby",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PG"
  },
  {
    "name": "Paraguay",
    "iso2": "PY",
    "callingCode": "+595",
    "currency": "PYG",
    "symbol": "PYG",
    "decimals": 0,
    "timezone": "America/Asuncion",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PY"
  },
  {
    "name": "Peru",
    "iso2": "PE",
    "callingCode": "+51",
    "currency": "PES",
    "symbol": "PES",
    "decimals": 2,
    "timezone": "America/Lima",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PE"
  },
  {
    "name": "Philippines",
    "iso2": "PH",
    "callingCode": "+63",
    "currency": "PHP",
    "symbol": "₱",
    "decimals": 2,
    "timezone": "Asia/Manila",
    "dateFormat": "MM/DD/YYYY",
    "locale": "en-PH"
  },
  {
    "name": "Pitcairn",
    "iso2": "PN",
    "callingCode": "",
    "currency": "NZD",
    "symbol": "NZ$",
    "decimals": 2,
    "timezone": "Pacific/Pitcairn",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PN"
  },
  {
    "name": "Poland",
    "iso2": "PL",
    "callingCode": "+48",
    "currency": "PLZ",
    "symbol": "PLZ",
    "decimals": 2,
    "timezone": "Europe/Warsaw",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PL"
  },
  {
    "name": "Portugal",
    "iso2": "PT",
    "callingCode": "+351",
    "currency": "PTE",
    "symbol": "PTE",
    "decimals": 2,
    "timezone": "Europe/Lisbon",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PT"
  },
  {
    "name": "Puerto Rico",
    "iso2": "PR",
    "callingCode": "+1",
    "currency": "ESP",
    "symbol": "ESP",
    "decimals": 2,
    "timezone": "America/Puerto_Rico",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PR"
  },
  {
    "name": "Qatar",
    "iso2": "QA",
    "callingCode": "+974",
    "currency": "QAR",
    "symbol": "QAR",
    "decimals": 2,
    "timezone": "Asia/Qatar",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-QA"
  },
  {
    "name": "Romania",
    "iso2": "RO",
    "callingCode": "+40",
    "currency": "ROL",
    "symbol": "ROL",
    "decimals": 2,
    "timezone": "Europe/Bucharest",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-RO"
  },
  {
    "name": "Russia",
    "iso2": "RU",
    "callingCode": "+7",
    "currency": "RUR",
    "symbol": "RUR",
    "decimals": 2,
    "timezone": "Europe/Kaliningrad",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-RU"
  },
  {
    "name": "Rwanda",
    "iso2": "RW",
    "callingCode": "+250",
    "currency": "RWF",
    "symbol": "RWF",
    "decimals": 0,
    "timezone": "Africa/Kigali",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-RW"
  },
  {
    "name": "Réunion",
    "iso2": "RE",
    "callingCode": "+262",
    "currency": "FRF",
    "symbol": "FRF",
    "decimals": 2,
    "timezone": "Indian/Reunion",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-RE"
  },
  {
    "name": "Saint Barthélemy",
    "iso2": "BL",
    "callingCode": "+590",
    "currency": "FRF",
    "symbol": "FRF",
    "decimals": 2,
    "timezone": "America/St_Barthelemy",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-BL"
  },
  {
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "iso2": "SH",
    "callingCode": "+290",
    "currency": "SHP",
    "symbol": "SHP",
    "decimals": 2,
    "timezone": "Atlantic/St_Helena",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SH"
  },
  {
    "name": "Saint Kitts and Nevis",
    "iso2": "KN",
    "callingCode": "+1",
    "currency": "XCD",
    "symbol": "EC$",
    "decimals": 2,
    "timezone": "America/St_Kitts",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-KN"
  },
  {
    "name": "Saint Lucia",
    "iso2": "LC",
    "callingCode": "+1",
    "currency": "XCD",
    "symbol": "EC$",
    "decimals": 2,
    "timezone": "America/St_Lucia",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-LC"
  },
  {
    "name": "Saint Martin (French part)",
    "iso2": "MF",
    "callingCode": "+590",
    "currency": "FRF",
    "symbol": "FRF",
    "decimals": 2,
    "timezone": "America/Marigot",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-MF"
  },
  {
    "name": "Saint Pierre and Miquelon",
    "iso2": "PM",
    "callingCode": "+508",
    "currency": "FRF",
    "symbol": "FRF",
    "decimals": 2,
    "timezone": "America/Miquelon",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-PM"
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "iso2": "VC",
    "callingCode": "+1",
    "currency": "XCD",
    "symbol": "EC$",
    "decimals": 2,
    "timezone": "America/St_Vincent",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-VC"
  },
  {
    "name": "Samoa",
    "iso2": "WS",
    "callingCode": "+685",
    "currency": "WST",
    "symbol": "WST",
    "decimals": 2,
    "timezone": "Pacific/Apia",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-WS"
  },
  {
    "name": "San Marino",
    "iso2": "SM",
    "callingCode": "+378",
    "currency": "ITL",
    "symbol": "ITL",
    "decimals": 2,
    "timezone": "Europe/San_Marino",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SM"
  },
  {
    "name": "Sao Tome and Principe",
    "iso2": "ST",
    "callingCode": "+239",
    "currency": "STD",
    "symbol": "STD",
    "decimals": 2,
    "timezone": "Africa/Sao_Tome",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-ST"
  },
  {
    "name": "Saudi Arabia",
    "iso2": "SA",
    "callingCode": "+966",
    "currency": "SAR",
    "symbol": "SAR",
    "decimals": 2,
    "timezone": "Asia/Riyadh",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SA"
  },
  {
    "name": "Senegal",
    "iso2": "SN",
    "callingCode": "+221",
    "currency": "XOF",
    "symbol": "F CFA",
    "decimals": 0,
    "timezone": "Africa/Dakar",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SN"
  },
  {
    "name": "Serbia",
    "iso2": "RS",
    "callingCode": "+381",
    "currency": "YUM",
    "symbol": "YUM",
    "decimals": 2,
    "timezone": "Europe/Belgrade",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-RS"
  },
  {
    "name": "Seychelles",
    "iso2": "SC",
    "callingCode": "+248",
    "currency": "SCR",
    "symbol": "SCR",
    "decimals": 2,
    "timezone": "Indian/Mahe",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SC"
  },
  {
    "name": "Sierra Leone",
    "iso2": "SL",
    "callingCode": "+232",
    "currency": "GBP",
    "symbol": "£",
    "decimals": 2,
    "timezone": "Africa/Freetown",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SL"
  },
  {
    "name": "Singapore",
    "iso2": "SG",
    "callingCode": "+65",
    "currency": "MYR",
    "symbol": "MYR",
    "decimals": 2,
    "timezone": "Asia/Singapore",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SG"
  },
  {
    "name": "Sint Maarten (Dutch part)",
    "iso2": "SX",
    "callingCode": "+1",
    "currency": "ANG",
    "symbol": "ANG",
    "decimals": 2,
    "timezone": "America/Lower_Princes",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SX"
  },
  {
    "name": "Slovakia",
    "iso2": "SK",
    "callingCode": "+421",
    "currency": "CSK",
    "symbol": "CSK",
    "decimals": 2,
    "timezone": "Europe/Bratislava",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SK"
  },
  {
    "name": "Slovenia",
    "iso2": "SI",
    "callingCode": "+386",
    "currency": "SIT",
    "symbol": "SIT",
    "decimals": 2,
    "timezone": "Europe/Ljubljana",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SI"
  },
  {
    "name": "Solomon Islands",
    "iso2": "SB",
    "callingCode": "+677",
    "currency": "AUD",
    "symbol": "A$",
    "decimals": 2,
    "timezone": "Pacific/Guadalcanal",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SB"
  },
  {
    "name": "Somalia",
    "iso2": "SO",
    "callingCode": "+252",
    "currency": "SOS",
    "symbol": "SOS",
    "decimals": 2,
    "timezone": "Africa/Mogadishu",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SO"
  },
  {
    "name": "South Africa",
    "iso2": "ZA",
    "callingCode": "+27",
    "currency": "ZAR",
    "symbol": "ZAR",
    "decimals": 2,
    "timezone": "Africa/Johannesburg",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-ZA"
  },
  {
    "name": "South Georgia and the South Sandwich Islands",
    "iso2": "GS",
    "callingCode": "",
    "currency": "GBP",
    "symbol": "£",
    "decimals": 2,
    "timezone": "Atlantic/South_Georgia",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GS"
  },
  {
    "name": "South Korea",
    "iso2": "KR",
    "callingCode": "+82",
    "currency": "KRO",
    "symbol": "KRO",
    "decimals": 2,
    "timezone": "Asia/Seoul",
    "dateFormat": "YYYY/MM/DD",
    "locale": "en-KR"
  },
  {
    "name": "South Sudan",
    "iso2": "SS",
    "callingCode": "+211",
    "currency": "SSP",
    "symbol": "SSP",
    "decimals": 2,
    "timezone": "Africa/Juba",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SS"
  },
  {
    "name": "Spain",
    "iso2": "ES",
    "callingCode": "+34",
    "currency": "ESP",
    "symbol": "ESP",
    "decimals": 2,
    "timezone": "Europe/Madrid",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-ES"
  },
  {
    "name": "Sri Lanka",
    "iso2": "LK",
    "callingCode": "+94",
    "currency": "LKR",
    "symbol": "LKR",
    "decimals": 2,
    "timezone": "Asia/Colombo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-LK"
  },
  {
    "name": "Sudan",
    "iso2": "SD",
    "callingCode": "+249",
    "currency": "EGP",
    "symbol": "EGP",
    "decimals": 2,
    "timezone": "Africa/Khartoum",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SD"
  },
  {
    "name": "Suriname",
    "iso2": "SR",
    "callingCode": "+597",
    "currency": "NLG",
    "symbol": "NLG",
    "decimals": 2,
    "timezone": "America/Paramaribo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SR"
  },
  {
    "name": "Svalbard and Jan Mayen",
    "iso2": "SJ",
    "callingCode": "+47",
    "currency": "NOK",
    "symbol": "NOK",
    "decimals": 2,
    "timezone": "Arctic/Longyearbyen",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SJ"
  },
  {
    "name": "Sweden",
    "iso2": "SE",
    "callingCode": "+46",
    "currency": "SEK",
    "symbol": "SEK",
    "decimals": 2,
    "timezone": "Europe/Stockholm",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SE"
  },
  {
    "name": "Switzerland",
    "iso2": "CH",
    "callingCode": "+41",
    "currency": "CHF",
    "symbol": "CHF",
    "decimals": 2,
    "timezone": "Europe/Zurich",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-CH"
  },
  {
    "name": "Syria",
    "iso2": "SY",
    "callingCode": "+963",
    "currency": "SYP",
    "symbol": "SYP",
    "decimals": 2,
    "timezone": "Asia/Damascus",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-SY"
  },
  {
    "name": "Taiwan",
    "iso2": "TW",
    "callingCode": "+886",
    "currency": "TWD",
    "symbol": "NT$",
    "decimals": 2,
    "timezone": "Asia/Taipei",
    "dateFormat": "YYYY/MM/DD",
    "locale": "en-TW"
  },
  {
    "name": "Tajikistan",
    "iso2": "TJ",
    "callingCode": "+992",
    "currency": "RUR",
    "symbol": "RUR",
    "decimals": 2,
    "timezone": "Asia/Dushanbe",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TJ"
  },
  {
    "name": "Tanzania",
    "iso2": "TZ",
    "callingCode": "+255",
    "currency": "TZS",
    "symbol": "TZS",
    "decimals": 2,
    "timezone": "Africa/Dar_es_Salaam",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TZ"
  },
  {
    "name": "Thailand",
    "iso2": "TH",
    "callingCode": "+66",
    "currency": "THB",
    "symbol": "THB",
    "decimals": 2,
    "timezone": "Asia/Bangkok",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TH"
  },
  {
    "name": "Timor-Leste",
    "iso2": "TL",
    "callingCode": "+670",
    "currency": "TPE",
    "symbol": "TPE",
    "decimals": 2,
    "timezone": "Asia/Dili",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TL"
  },
  {
    "name": "Togo",
    "iso2": "TG",
    "callingCode": "+228",
    "currency": "XOF",
    "symbol": "F CFA",
    "decimals": 0,
    "timezone": "Africa/Lome",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TG"
  },
  {
    "name": "Tokelau",
    "iso2": "TK",
    "callingCode": "+690",
    "currency": "NZD",
    "symbol": "NZ$",
    "decimals": 2,
    "timezone": "Pacific/Fakaofo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TK"
  },
  {
    "name": "Tonga",
    "iso2": "TO",
    "callingCode": "+676",
    "currency": "TOP",
    "symbol": "TOP",
    "decimals": 2,
    "timezone": "Pacific/Tongatapu",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TO"
  },
  {
    "name": "Trinidad and Tobago",
    "iso2": "TT",
    "callingCode": "+1",
    "currency": "TTD",
    "symbol": "TTD",
    "decimals": 2,
    "timezone": "America/Port_of_Spain",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TT"
  },
  {
    "name": "Tunisia",
    "iso2": "TN",
    "callingCode": "+216",
    "currency": "TND",
    "symbol": "TND",
    "decimals": 3,
    "timezone": "Africa/Tunis",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TN"
  },
  {
    "name": "Turkey",
    "iso2": "TR",
    "callingCode": "+90",
    "currency": "TRL",
    "symbol": "TRL",
    "decimals": 2,
    "timezone": "Europe/Istanbul",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TR"
  },
  {
    "name": "Turkmenistan",
    "iso2": "TM",
    "callingCode": "+993",
    "currency": "SUR",
    "symbol": "SUR",
    "decimals": 2,
    "timezone": "Asia/Ashgabat",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TM"
  },
  {
    "name": "Turks and Caicos Islands",
    "iso2": "TC",
    "callingCode": "+1",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "America/Grand_Turk",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TC"
  },
  {
    "name": "Tuvalu",
    "iso2": "TV",
    "callingCode": "+688",
    "currency": "AUD",
    "symbol": "A$",
    "decimals": 2,
    "timezone": "Pacific/Funafuti",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-TV"
  },
  {
    "name": "UAE",
    "iso2": "AE",
    "callingCode": "+971",
    "currency": "AED",
    "symbol": "AED",
    "decimals": 2,
    "timezone": "Asia/Dubai",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AE"
  },
  {
    "name": "Uganda",
    "iso2": "UG",
    "callingCode": "+256",
    "currency": "UGS",
    "symbol": "UGS",
    "decimals": 2,
    "timezone": "Africa/Kampala",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-UG"
  },
  {
    "name": "Ukraine",
    "iso2": "UA",
    "callingCode": "+380",
    "currency": "SUR",
    "symbol": "SUR",
    "decimals": 2,
    "timezone": "Europe/Simferopol",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-UA"
  },
  {
    "name": "United Kingdom",
    "iso2": "GB",
    "callingCode": "+44",
    "currency": "GBP",
    "symbol": "£",
    "decimals": 2,
    "timezone": "Europe/London",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-GB"
  },
  {
    "name": "United States",
    "iso2": "US",
    "callingCode": "+1",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "America/New_York",
    "dateFormat": "MM/DD/YYYY",
    "locale": "en-US"
  },
  {
    "name": "United States Minor Outlying Islands",
    "iso2": "UM",
    "callingCode": "",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "Pacific/Midway",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-UM"
  },
  {
    "name": "Uruguay",
    "iso2": "UY",
    "callingCode": "+598",
    "currency": "UYP",
    "symbol": "UYP",
    "decimals": 2,
    "timezone": "America/Montevideo",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-UY"
  },
  {
    "name": "Uzbekistan",
    "iso2": "UZ",
    "callingCode": "+998",
    "currency": "UZS",
    "symbol": "UZS",
    "decimals": 2,
    "timezone": "Asia/Samarkand",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-UZ"
  },
  {
    "name": "Vanuatu",
    "iso2": "VU",
    "callingCode": "+678",
    "currency": "VUV",
    "symbol": "VUV",
    "decimals": 2,
    "timezone": "Pacific/Efate",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-VU"
  },
  {
    "name": "Venezuela",
    "iso2": "VE",
    "callingCode": "+58",
    "currency": "VEB",
    "symbol": "VEB",
    "decimals": 2,
    "timezone": "America/Caracas",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-VE"
  },
  {
    "name": "Vietnam",
    "iso2": "VN",
    "callingCode": "+84",
    "currency": "VNN",
    "symbol": "VNN",
    "decimals": 2,
    "timezone": "Asia/Ho_Chi_Minh",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-VN"
  },
  {
    "name": "Virgin Islands, British",
    "iso2": "VG",
    "callingCode": "+1",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "America/Tortola",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-VG"
  },
  {
    "name": "Virgin Islands, U.S.",
    "iso2": "VI",
    "callingCode": "+1",
    "currency": "USD",
    "symbol": "$",
    "decimals": 2,
    "timezone": "America/St_Thomas",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-VI"
  },
  {
    "name": "Wallis and Futuna",
    "iso2": "WF",
    "callingCode": "+681",
    "currency": "XPF",
    "symbol": "CFPF",
    "decimals": 2,
    "timezone": "Pacific/Wallis",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-WF"
  },
  {
    "name": "Western Sahara",
    "iso2": "EH",
    "callingCode": "+212",
    "currency": "MAD",
    "symbol": "MAD",
    "decimals": 2,
    "timezone": "Africa/El_Aaiun",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-EH"
  },
  {
    "name": "Yemen",
    "iso2": "YE",
    "callingCode": "+967",
    "currency": "YER",
    "symbol": "YER",
    "decimals": 2,
    "timezone": "Asia/Aden",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-YE"
  },
  {
    "name": "Zambia",
    "iso2": "ZM",
    "callingCode": "+260",
    "currency": "ZMK",
    "symbol": "ZMK",
    "decimals": 2,
    "timezone": "Africa/Lusaka",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-ZM"
  },
  {
    "name": "Zimbabwe",
    "iso2": "ZW",
    "callingCode": "+263",
    "currency": "RHD",
    "symbol": "RHD",
    "decimals": 2,
    "timezone": "Africa/Harare",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-ZW"
  },
  {
    "name": "Åland Islands",
    "iso2": "AX",
    "callingCode": "+358",
    "currency": "EUR",
    "symbol": "€",
    "decimals": 2,
    "timezone": "Europe/Mariehamn",
    "dateFormat": "DD/MM/YYYY",
    "locale": "en-AX"
  }
] as CountryCatalogEntry[];

export const COUNTRY_BY_NAME = Object.fromEntries(COUNTRY_CATALOG.map((country) => [country.name, country])) as Record<string, CountryCatalogEntry>;
export const COUNTRY_BY_ISO2 = Object.fromEntries(COUNTRY_CATALOG.map((country) => [country.iso2, country])) as Record<string, CountryCatalogEntry>;
export function getCatalogCountry(name?: string | null) { return name ? COUNTRY_BY_NAME[name] : undefined; }
