-- Phase 7: Paddle discount automation and redemption attribution.
-- Safe to run on an existing Rivox database.

alter table public.admin_promo_codes
  add column if not exists paddle_sync_status text not null default 'not_synced'
    check (paddle_sync_status in ('not_synced','syncing','synced','error','archived')),
  add column if not exists paddle_last_synced_at timestamptz,
  add column if not exists paddle_last_error text,
  add column if not exists paddle_recur boolean not null default false,
  add column if not exists paddle_max_recurring_intervals integer,
  add column if not exists paddle_currency_code text not null default 'USD',
  add column if not exists paddle_restrict_to text[] not null default '{}';

create table if not exists public.offer_redemptions (
  id bigint generated by default as identity primary key,
  offer_id uuid references public.admin_promo_codes(id) on delete set null,
  provider text not null default 'paddle',
  provider_event_id text not null unique,
  provider_transaction_id text,
  provider_subscription_id text,
  paddle_discount_id text,
  user_id uuid references auth.users(id) on delete set null,
  plan text,
  billing_cycle text,
  amount numeric,
  discount_amount numeric,
  currency text,
  status text not null default 'completed',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists offer_redemptions_offer_created_idx
  on public.offer_redemptions(offer_id, created_at desc);

alter table public.offer_redemptions enable row level security;

drop policy if exists owner_read_offer_redemptions on public.offer_redemptions;
create policy owner_read_offer_redemptions
on public.offer_redemptions for select to authenticated
using ((auth.jwt() ->> 'email') = 'mz7123272@gmail.com');

-- Public users never write redemption rows directly; webhook service role handles writes.
revoke insert, update, delete on public.offer_redemptions from anon, authenticated;
grant select on public.offer_redemptions to authenticated;
